# Generated by Django 6.0 on 2025-12-19 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('prd_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('prd_ingredients', models.TextField(blank=True, verbose_name='Ingrédients')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description_cmd', models.CharField(max_length=200, verbose_name='Description')),
                ('Date_cmd', models.DateField(default=django.utils.timezone.now, verbose_name='Date de commande')),
                ('Produit_cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-Date_cmd'],
            },
        ),
    ]
